import flet as ft

class Frontend():

    def main(self,page:ft.Page):
        page.padding = 0
        page.bgcolor = ft.colors.WHITE
        page.scroll = ft.ScrollMode.AUTO
        page.window_width = 1920
        

        layout = ft.Column(
            spacing=0,
            controls=[
                header := ft.Container(
                    padding=ft.padding.only(left=20),
                    height=90,
                    bgcolor="#232452",
                    content=(
                        ft.Row(
                            controls=[
                                ft.Image(
                                    col=1,
                                    src=f"hello.PNG",
                                    width=100,
                                    height=100,
                                    scale=ft.Scale(scale=1.6)
                                ),
                                ft.Container(
                                    padding=ft.padding.only(left=1400),
                                    alignment=ft.alignment.center_right,
                                    content=(
                                        ft.Row(
                                            controls=[
                                                ft.TextButton(
                                                    width=90,
                                                    height=30,
                                                    on_click=lambda _:page.scroll_to(530),
                                                    style=ft.ButtonStyle(
                                                        bgcolor={
                                                            ft.MaterialState.DEFAULT:"#232452",
                                                        },
                                                        color={
                                                            ft.MaterialState.DEFAULT:"#D94389"
                                                        },
                                                        text_style={
                                                            ft.ControlState.DEFAULT:ft.TextStyle(weight=ft.FontWeight.NORMAL,size=15,font_family="comic sans"),
                                                        },
                                                        shape={
                                                            ft.ControlState.DEFAULT:ft.RoundedRectangleBorder(radius=ft.border_radius.all(6))
                                                        }
                                                    ),
                                                    text=("Serviços")
                                                ),
                                                ft.TextButton(
                                                    width=90,
                                                    height=30,
                                                    on_click=lambda _:page.scroll_to(1460),
                                                    style=ft.ButtonStyle(
                                                        bgcolor={
                                                            ft.MaterialState.DEFAULT:"#232452",
                                                        },
                                                        color={
                                                            ft.MaterialState.DEFAULT:"#D94389"
                                                        },
                                                        text_style={
                                                            ft.ControlState.DEFAULT:ft.TextStyle(weight=ft.FontWeight.NORMAL,size=15,font_family="comic sans"),
                                                        },
                                                        shape={
                                                            ft.ControlState.DEFAULT:ft.RoundedRectangleBorder(radius=ft.border_radius.all(6))
                                                        }
                                                    ),
                                                    text=("Sobre")
                                                ),        
                                                ft.TextButton(
                                                    width=90,
                                                    height=30,
                                                    on_click=lambda _:page.scroll_to(2000),
                                                    style=ft.ButtonStyle(
                                                        bgcolor={
                                                            ft.MaterialState.DEFAULT:"#232452",
                                                        },
                                                        color={
                                                            ft.MaterialState.DEFAULT:"#D94389"
                                                        },
                                                        text_style={
                                                            ft.ControlState.DEFAULT:ft.TextStyle(weight=ft.FontWeight.NORMAL,size=15,font_family="comic sans"),
                                                        },
                                                        shape={
                                                            ft.ControlState.DEFAULT:ft.RoundedRectangleBorder(radius=ft.border_radius.all(6))
                                                        }
                                                    ),
                                                    text=("Contato")
                                                )
                                            ]
                                        )
                                    )
                                )
                            ]
                        )
                    )
                ),
                section1 := ft.Container(
                    gradient=ft.LinearGradient(
                        begin=ft.alignment.top_right,
                        end=ft.alignment.bottom_left,
                        colors=("#DFE2F2","#ddcae6","#d4b6ff")
                    ),
                    height=620,
                    content=(
                        ft.Row(
                            alignment=ft.MainAxisAlignment.CENTER,
                            spacing= 100,
                            controls=[
                                ft.Container(
                                    
                                    height=400,
                                    width=500,
                                    padding=60,
                                    border_radius=10,
                                    bgcolor="#232452",
                                    content=(
                                        ft.Image(
                                            src="limpeza.png"
                                        )
                                    )
                                ),
                                ft.Container(
                                    margin=ft.margin.only(top=180),
                                    content=(
                                        ft.Column(
                                            spacing=0,
                                            controls=[
                                                ft.Text(
                                                    value="SHYRLEY STEFÂNIA",
                                                    size=13,
                                                    color="#D94389"
                                                ),
                                                ft.Text(
                                                    value="Transforme sua casa em um\nlar limpo e acolhedor, porque você\nmerece um ambiente impecável!",
                                                    size=40,
                                                    weight=ft.FontWeight.BOLD,
                                                    color="#232452"
                                                )
                                            ]
                                        )
                                    )
                                )
                            ]
                        )
                    )
                ),
                section2 := ft.Container(
                    height=500,
                    margin=ft.margin.only(top=70,left=200,right=200),
                    alignment=ft.alignment.top_center,
                    content=(
                        ft.Column(
                            spacing=60,
                            controls=[
                                ft.Row(
                                    alignment=ft.MainAxisAlignment.CENTER,
                                    controls=[
                                        ft.Text(
                                            value="NOSSOS SERVIÇOS",
                                            size=30,
                                            color="#D94389",
                                            weight=ft.FontWeight.BOLD
                                        )
                                    ]
                                ),
                                ft.ResponsiveRow(
                                    columns=4,
                                    spacing=30,
                                    controls=[
                                        ft.Container(
                                            col=1,
                                            content=(
                                                ft.Column(
                                                    spacing=10,
                                                    controls=[
                                                        ft.Image(
                                                            src="faxineira.jpg",
                                                            border_radius=8,
                                                        ),
                                                        ft.TextButton(    
                                                            text=("Faxineira"),
                                                            width=400,
                                                            height=40,
                                                            style=ft.ButtonStyle(
                                                                bgcolor={
                                                                    ft.MaterialState.DEFAULT:"#D94389", 
                                                                    ft.MaterialState.HOVERED:"#232452"           
                                                                },
                                                                shape={
                                                                    ft.MaterialState.DEFAULT:ft.RoundedRectangleBorder(ft.border_radius.all(4))
                                                                },
                                                                color={
                                                                    ft.MaterialState.DEFAULT:ft.colors.WHITE
                                                                },
                                                                text_style={
                                                                    ft.MaterialState.DEFAULT:ft.TextStyle(size=18,weight=ft.FontWeight.BOLD)
                                                                }
                                                            ),
                                                        )
                                                    ]
                                                )
                                            )
                                        ),
                                        ft.Container(
                                            col=1,
                                            content=(
                                                ft.Column(  
                                                    spacing=10,
                                                    controls=[
                                                        ft.Image(
                                                            src="lavadeira.jpg",
                                                            border_radius=8,
                                                        ),
                                                        ft.TextButton(    
                                                            text="Lavadeira",
                                                            width=400,
                                                            height=40,
                                                            style=ft.ButtonStyle(
                                                                bgcolor={
                                                                    ft.MaterialState.DEFAULT:"#D94389", 
                                                                    ft.MaterialState.HOVERED:"#232452"           
                                                                },
                                                                shape={
                                                                    ft.MaterialState.DEFAULT:ft.RoundedRectangleBorder(ft.border_radius.all(4))
                                                                },
                                                                color={
                                                                    ft.MaterialState.DEFAULT:ft.colors.WHITE
                                                                },
                                                                text_style={
                                                                    ft.MaterialState.DEFAULT:ft.TextStyle(size=18,weight=ft.FontWeight.BOLD)
                                                                }
                                                            )
                                                        )
                                                    ]
                                                )
                                            )
                                        ),
                                        ft.Container(
                                            col=1,
                                            content=(
                                                ft.Column(
                                                    spacing=10,
                                                    controls=[
                                                        ft.Image(
                                                            src="cozinheira.jpg",
                                                            border_radius=8
                                                        ),
                                                        ft.TextButton(    
                                                            text="Cozinheira",
                                                            width=400,
                                                            height=40,
                                                            style=ft.ButtonStyle(
                                                                bgcolor={
                                                                    ft.MaterialState.DEFAULT:"#D94389", 
                                                                    ft.MaterialState.HOVERED:"#232452"           
                                                                },
                                                                shape={
                                                                    ft.MaterialState.DEFAULT:ft.RoundedRectangleBorder(ft.border_radius.all(4))
                                                                },
                                                                color={
                                                                    ft.MaterialState.DEFAULT:ft.colors.WHITE
                                                                },
                                                                text_style={
                                                                    ft.MaterialState.DEFAULT:ft.TextStyle(size=18,weight=ft.FontWeight.BOLD)
                                                                }
                                                            ),
                                                        )
                                                    ]
                                                )
                                            )
                                        ),
                                        ft.Container(
                                            col=1,
                                            content=(
                                                ft.Column(
                                                    spacing=10,
                                                    controls=[
                                                        ft.Image(
                                                            src="passadeira.jpg",border_radius=8
                                                        ),
                                                        ft.TextButton(    
                                                            text="Passadeira",
                                                            width=400,
                                                            height=40,
                                                            style=ft.ButtonStyle(
                                                                bgcolor={
                                                                    ft.MaterialState.DEFAULT:"#D94389", 
                                                                    ft.MaterialState.HOVERED:"#232452"           
                                                                },
                                                                shape={
                                                                    ft.MaterialState.DEFAULT:ft.RoundedRectangleBorder(ft.border_radius.all(4))
                                                                },
                                                                color={
                                                                    ft.MaterialState.DEFAULT:ft.colors.WHITE
                                                                },
                                                                text_style={
                                                                    ft.MaterialState.DEFAULT:ft.TextStyle(size=18,weight=ft.FontWeight.BOLD)
                                                                }
                                                            )
                                                        )
                                                    ]
                                                )
                                            )
                                        )
                                    ]
                                )
                            ]
                        ) 
                    )
                ),
                section3 := ft.Container(
                    height=200,
                    bgcolor="#232452"
                ),
                section4 :=ft.Container(
                    height=950,
                    bgcolor="#53d4b6ff",
                    content=(
                        ft.ResponsiveRow(
                            spacing=0,
                            columns=12,
                            controls=[
                                ft.Container(
                                    padding=ft.padding.only(top=120,right=50),
                                    col=6,
                                    opacity=1.0,
                                    content=(
                                        ft.Column(
                                            controls=[
                                                ft.Container(
                                                    alignment=ft.alignment.center,
                                                    margin=ft.margin.only(bottom=110),
                                                    content=(
                                                        ft.Image(
                                                            src="faxineira2.jpg",
                                                            border_radius=10
                                                        )   
                                                    )
                                                ),
                                                ft.Container(
                                                    margin=ft.margin.only(left=60),
                                                    content=(
                                                        ft.Text(
                                                            value='O nome "Hello Limpeza" foi escolhido por Shyrley para transmitir uma sensação de acolhimento e confiança. Ela queria que seus clientes sentissem que estavam chamando uma amiga de longa data para ajudar em suas casas. Desde o início, a empresa se destacou pela qualidade e pela atenção aos detalhes, conquistando a confiança de seus clientes.\n\nA "Hello Limpeza" oferece uma variedade de serviços, incluindo faxina, cozinheira, passadeira, diarista e lavadeira. Shyrley sempre acreditou que cada lar é único e que cada cliente merece um serviço personalizado. Por isso, ela e sua equipe trabalham com o intuito de entender as necessidades específicas de cada cliente, garantindo que suas expectativas sejam superadas.\n\nCom o passar dos anos, a empresa cresceu. Shyrley contratou profissionais talentosos e dedicados, todos com a mesma paixão por oferecer um excelente atendimento. Ela investiu em treinamentos e workshops, para que sua equipe estivesse sempre atualizada sobre as melhores práticas de limpeza e cuidados domésticos.',
                                                            color="#232452",
                                                            size=15
                                                        )
                                                    )
                                                )
                                            ]
                                        )
                                    )
                                ),
                                ft.Container(
                                    col=6,
                                    padding=ft.padding.only(top=100,right=50),
                                    alignment=ft.alignment.center,
                                    content=(
                                        ft.Column(
                                            controls=[
                                                ft.Text(
                                                    value="Sobre",
                                                    color="#D94389",
                                                    size=35,
                                                    style=ft.TextStyle(
                                                        weight=ft.FontWeight.BOLD
                                                    )
                                                ),
                                                ft.Text(
                                                    value='Shyrley Stefânia da Mata Fernandes, aos 47 anos, é um exemplo inspirador de determinação e empreendedorismo. Nascida e criada em uma pequena cidade, Shyrley sempre teve um espírito forte e uma visão clara de que poderia fazer a diferença na vida das pessoas ao seu redor. Desde jovem, trabalhou em diversos empregos, onde desenvolveu habilidades valiosas em organização, culinária e cuidado com a casa. Essa experiência a moldou e a preparou para um grande desafio que viria mais tarde. \n\nA ideia de criar a "Hello Limpeza" surgiu em um momento de reflexão. Após anos de trabalho em empresas de limpeza, Shyrley percebeu que havia uma demanda crescente por serviços domésticos de qualidade, que não apenas atendessem às necessidades básicas, mas que também oferecessem um toque personalizado. Com isso em mente, decidiu fundar sua própria empresa em 2015, apostando no potencial do mercado de serviços domésticos.',
                                                    color="#232452",
                                                    size=15
                                                ),
                                                ft.Container(
                                                    alignment=ft.alignment.center,
                                                    margin=ft.margin.only(top=120,left=30),
                                                    content=(
                                                        ft.Image(
                                                            src="faxineira2.jpg",
                                                            border_radius=10)
                                                    )
                                                )
                                            ]
                                        )
                                    )
                                ),
                            ]
                        )
                    )
                ),
                section5 := ft.Container(
                    padding=ft.padding.only(left=30, top=20),
                    height=400, 
                    bgcolor="#232452",
                    content=(
                        ft.Row(
                            spacing=200,
                            controls=[
                                ft.Column(
                                    controls=[
                                        ft.Image(
                                            src=f"hello.PNG",
                                            width=80,
                                            height=80,
                                            scale=ft.Scale(scale=1.6)
                                        ),
                                        ft.Row(
                                            alignment=ft.MainAxisAlignment.CENTER,
                                            spacing=15,
                                            controls=[
                                                ft.Image(
                                                    src="twitter.png",
                                                    width=31,
                                                    height=31
                                                ),
                                                ft.Image(
                                                    src="zap.webp",
                                                    width=38,
                                                    height=38
                                                ),
                                                ft.Image(
                                                    src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Instagram_logo_2022.svg/1024px-Instagram_logo_2022.svg.png",
                                                    width=38,
                                                    height=38
                                                )
                                            ]
                                        )
                                    ]
                                ),
                                ft.Container(
                                    
                                    content=(
                                        ft.Column(
                                            spacing=5,
                                            alignment=ft.MainAxisAlignment.CENTER,
                                            controls=[
                                                ft.Text(
                                                    value='Precisando de ajuda com os serviços domésticos da sua casa? \nEntre em contato conosco para agendar um horário!\nNossa equipe está pronta para oferecer o melhor atendimento, garantindo um lar limpo e acolhedor.\nAgende já e sinta a diferença!\nLembre-se:',
                                                    size=20,
                                                    color=ft.colors.WHITE
                                                ),
                                                ft.Text(
                                                    value="Um lar limpo é um lar feliz!",
                                                    size=22,
                                                    color="#D94389",
                                                    weight=ft.FontWeight.BOLD
                                                )
                                            ]
                                        )
                                    )
                                )
                            ]
                        )
                    )
                ),
                baseboard := ft.Container(
                    alignment=ft.alignment.center,
                    height=80,
                    bgcolor="#D94389",
                    content=(
                        ft.Text(value="Hello Limpeza - © 2015 - 2024 - Todos os direitos reservados",size=12    )
                    )
                )   
            ]
        )
        page.add(layout)

if __name__ == "__main__":
    app = Frontend()
    ft.app(target=app.main,assets_dir="assets")